import { useState } from 'react';
import { motion, type TargetAndTransition } from 'motion/react';
import { cn } from '@/lib/utils';
import { useReducedMotion } from '@/lib/prefs';

export type MascotState = 'idle' | 'happy' | 'sniffing' | 'sleeping' | 'eating' | 'sad';

// Remember which art files are missing so we don't flash a broken image on every mount.
const missing = new Set<string>();

// Gentle whole-body motion only; expression (blink, scan, standby pulse) is animated inside the SVG art.
const MOTION: Record<MascotState, TargetAndTransition> = {
  idle: { y: [0, -2, 0], transition: { duration: 4.2, repeat: Infinity, ease: 'easeInOut' } },
  happy: { y: [0, -6, 0, -3, 0], transition: { duration: 1.1, repeat: Infinity, repeatDelay: 1.1, ease: 'easeOut' } },
  sniffing: { x: [0, -2, 2, 0], transition: { duration: 1.2, repeat: Infinity, ease: 'easeInOut' } },
  sleeping: { scale: [1, 1.015, 1], transition: { duration: 4, repeat: Infinity, ease: 'easeInOut' } },
  eating: { y: [0, 2, 0], transition: { duration: 0.7, repeat: Infinity, ease: 'easeInOut' } },
  sad: { y: [2, 3, 2], transition: { duration: 4, repeat: Infinity, ease: 'easeInOut' } },
};

export function Mascot({
  state = 'idle',
  size = 120,
  className,
  label,
  still,
}: {
  state?: MascotState;
  size?: number;
  className?: string;
  label?: string;
  /** Disable idle motion (e.g. in dense lists). */
  still?: boolean;
}) {
  const reduce = useReducedMotion();
  // The .svg carries the visor animation (blink, glint, scan, standby pulse); the .png is its
  // static first frame, used when motion is reduced or if the SVG can't load.
  const sources = (reduce ? ['png'] : ['svg', 'png']).map((ext) => `/mascot/${state}.${ext}`);
  const [, setMissingTick] = useState(0);
  const src = sources.find((s) => !missing.has(s));
  const animate = reduce || still ? undefined : MOTION[state];
  return (
    <motion.div
      role="img"
      aria-label={label ?? `Woltron the dog, ${state}`}
      className={cn('relative inline-block shrink-0 select-none', className)}
      style={{ width: size, height: size, transformOrigin: '50% 85%' }}
      animate={animate}
    >
      {src ? (
        <img
          key={src}
          src={src}
          alt=""
          width={size}
          height={size}
          draggable={false}
          className="size-full object-contain drop-shadow-[0_8px_14px_rgb(43_26_51_/_0.18)]"
          onError={() => {
            missing.add(src);
            setMissingTick((n) => n + 1);
          }}
        />
      ) : (
        <RoboFace state={state} />
      )}
    </motion.div>
  );
}

/**
 * Inline vector fallback used if the rendered PNGs fail to load: a simplified
 * version of the robot dog (pearl shell, dark visor, chartreuse LED eyes).
 * The full artwork is generated by assets/scripts/robodog.py.
 */
function RoboFace({ state }: { state: MascotState }) {
  const droop = state === 'sad' || state === 'sleeping';
  const ear = droop ? -128 : state === 'happy' ? -14 : -24;
  const led = state === 'sleeping' ? 0.5 : 1;
  const arcUp = state === 'happy' || state === 'eating';
  return (
    <svg viewBox="0 0 120 120" className="size-full" aria-hidden>
      <defs>
        <linearGradient id="rf-shell" x1="0.25" y1="0" x2="0.75" y2="1">
          <stop offset="0" stopColor="#fbf8f6" />
          <stop offset="0.6" stopColor="#ece4e0" />
          <stop offset="1" stopColor="#ab9caa" />
        </linearGradient>
        <linearGradient id="rf-graph" x1="0" y1="0" x2="0.3" y2="1">
          <stop offset="0" stopColor="#55445f" />
          <stop offset="1" stopColor="#1c1323" />
        </linearGradient>
      </defs>
      {[1, -1].map((side) => (
        <g key={side} transform={side === -1 ? 'matrix(-1 0 0 1 120 0)' : undefined}>
          <g transform={`translate(39 34) rotate(${ear})`}>
            <path d="M-10 2 C-12.5 -9 -10 -21.5 -3 -30 C-1.5 -32 1.5 -32 3 -29.8 C9 -20.6 12.2 -9.4 10.3 2 Z" fill={droop ? '#6e5e78' : 'url(#rf-shell)'} />
            {!droop && <path d="M-5 -3 C-6 -12 -4.5 -19.7 0 -25 C4 -19 6 -12 5 -3 Z" fill="url(#rf-graph)" />}
          </g>
        </g>
      ))}
      <path d="M60 22.5 C77.3 22.5 90.5 29 93.3 43.6 C95.6 55.8 94.7 67 89 76.4 C82.5 86.7 71.7 91.4 60 91.4 C48.3 91.4 37.5 86.7 31 76.4 C25.3 67 24.4 55.8 26.7 43.6 C29.5 29 42.7 22.5 60 22.5 Z" fill="url(#rf-shell)" />
      <path d="M60 35.2 C78.3 35.2 90 38 92.4 47.8 C94.7 59 87.2 68 74.5 69.4 C68 70 64.2 67.5 60 67.5 C55.8 67.5 52 70 45.5 69.4 C32.8 68 25.3 59 27.6 47.8 C30 38 41.7 35.2 60 35.2 Z" fill="url(#rf-graph)" />
      <g fill="none" stroke="var(--ball)" strokeLinecap="round" strokeWidth="3" opacity={led}>
        {state === 'sad' ? (
          <>
            <path d="M44 49 L52 53 L52 56" />
            <path d="M76 49 L68 53 L68 56" />
          </>
        ) : arcUp ? (
          <>
            <path d="M43.5 54 Q48.3 46 53 54" />
            <path d="M67 54 Q71.7 46 76.5 54" />
          </>
        ) : state === 'sleeping' ? (
          <>
            <path d="M43.5 51 Q48.3 56 53 51" />
            <path d="M67 51 Q71.7 56 76.5 51" />
          </>
        ) : (
          <>
            <ellipse cx="48.3" cy="52" rx="3.6" ry={state === 'sniffing' ? 2 : 5.2} fill="var(--ball)" stroke="none" />
            <ellipse cx="71.7" cy="52" rx="3.6" ry={state === 'sniffing' ? 2 : 5.2} fill="var(--ball)" stroke="none" />
          </>
        )}
      </g>
      <path d="M60 58 C66.6 58 70 62.4 71.7 68.4 C78.3 69.8 83.4 74.5 83.4 81 C83.4 88 74 91.4 60 91.4 C46 91.4 36.6 88 36.6 81 C36.6 74.5 41.7 69.8 48.3 68.4 C50 62.4 53.4 58 60 58 Z" fill="url(#rf-shell)" />
      <path d="M60 75.5 C54.8 75.5 51.6 72.6 51.6 69.6 C51.6 66.8 54.8 65.6 60 65.6 C65.2 65.6 68.4 66.8 68.4 69.6 C68.4 72.6 65.2 75.5 60 75.5 Z" fill="url(#rf-graph)" />
      {state === 'eating' && <circle cx="60" cy="94" r="9" fill="var(--ball)" stroke="#2b1a33" strokeOpacity="0.3" />}
    </svg>
  );
}
