// Generated by scripts/capture-fixtures.ts — do not edit by hand.
import listing from './venues.json';
import v_amore_mio from './venues/amore-mio.json';
import v_burger_station_23 from './venues/burger-station-23.json';
import v_china_class_tel_aviv from './venues/china-class-tel-aviv.json';
import v_extreme_pizza_tel_aviv from './venues/extreme-pizza-tel-aviv.json';
import v_koko_neko from './venues/koko-neko.json';
import v_ma_pau_nachlat_binyamin from './venues/ma-pau-nachlat-binyamin.json';
import v_nam_king_george from './venues/nam-king-george.json';
import v_nona_cafe from './venues/nona-cafe.json';
import v_roll_n_roll from './venues/roll-n-roll.json';
import v_taqueria_1 from './venues/taqueria-1.json';
import v_the_poke_ramat_gan from './venues/the-poke-ramat-gan.json';
import v_vong_midtown_tel_aviv from './venues/vong-midtown-tel-aviv.json';

export const venueListing: any = listing;
export const venueFixtures: Record<string, any> = {
  "amore-mio": v_amore_mio,
  "burger-station-23": v_burger_station_23,
  "china-class-tel-aviv": v_china_class_tel_aviv,
  "extreme-pizza-tel-aviv": v_extreme_pizza_tel_aviv,
  "koko-neko": v_koko_neko,
  "ma-pau-nachlat-binyamin": v_ma_pau_nachlat_binyamin,
  "nam-king-george": v_nam_king_george,
  "nona-cafe": v_nona_cafe,
  "roll-n-roll": v_roll_n_roll,
  "taqueria-1": v_taqueria_1,
  "the-poke-ramat-gan": v_the_poke_ramat_gan,
  "vong-midtown-tel-aviv": v_vong_midtown_tel_aviv,
};
